# Generated by Django 5.0 on 2023-12-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_atividade', models.TextField()),
                ('data_recepcao', models.DateField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacao', models.TextField()),
                ('status', models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Em análise', 'Em análise'), ('Pendente', 'Pendente'), ('Concluído', 'Concluído'), ('Suspenso', 'Suspenso')], max_length=20)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.atividade')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.municipio')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.nome')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.setor')),
            ],
        ),
    ]
